### ISSUE TITLE
视频贴物3D投射Mac笔记本显示异常

### ISSUE THREAD

**Issue by yangdengxian** [marsgis/mars3d-vue-example#1]
哈喽，你好，我发现视频3D贴物投射，在Mac笔记本视频会被模型（3D tiles）给挡住，没有起到贴物效果。但是在Windows本是正常的，请问一下有什么好的方式可以解决吗？谢谢了

**Comment by muyao1987** [comment]
不同GPU对webgl支持度可能有差距，如果有您描述的这个问题，目前没有太好办法。
