### ISSUE TITLE
timeline时间线 时间标与时钟currentTime对不上

### ISSUE THREAD

**Issue by liseri** [marsgis/mars3d-vue-example#10]
**版本**： 3.5.0
**问题**：如下两种情况：
第1种情况如下图表示 时钟暂停状态，时钟的时间与时间线上的时间标能对的上； **正常**
![1688715663398_ACDCD192-20CA-47b5-A59F-BC7E3D1C5381](https://github.com/marsgis/mars3d-vue-example/assets/2908276/0b7d6811-1973-44e7-93ed-687ce92dd9d1)

第2种情况如下图表示 时钟启动状态，时钟的时间与时间线上的时间标对不上(currentTime为9点多，时间线上的时间线还没到9点)； **异常**
![1688715695967_CA5486EE-3C37-4da1-B39B-C8EA0946A313](https://github.com/marsgis/mars3d-vue-example/assets/2908276/c155b1be-f456-44fa-8854-4010af0c7b80)

**配置代码**：
```
const mapOptions = {
  scene: {
    clock: {
      startTime: "2022-12-23 07:30:00",
      stopTime: "2022-12-23 10:30:00",
      currentTime: "2022-12-23 09:00:00",
      multiplier: 1
    }
  },
  control: {
    clockAnimate: true,
    timeline: true
  }
}

const mapLoaded = (mapInstance: mars3d.Map) => {
  map = mapInstance

  if (map.clock && map.controls.timeline) {
    const startTime = map.clock.startTime.clone()
    const stopTime = map.clock.stopTime.clone()
    const currentTime = map.clock.currentTime.clone()

    map.controls.timeline.zoomTo(startTime, stopTime)
  }
}
```

**Comment by muyao1987** [comment]
谢谢反馈，将在v3.5.15版本修复
