### ISSUE TITLE
二三维切换时 矢量图形显示位置有差别

### ISSUE THREAD

**Issue by liseri** [marsgis/mars3d-vue-example#11]
版本：线上最新example页面上做测试
示例：http://mars3d.cn/editor-vue.html?id=layer-graphic/draw/draw-model
操作：进入示例页面后，在图层中点选 石化工厂； 然后点标绘，scale=0.1
问题：如图，切换二三维后， 飞机的位置有位移，不一致； 但是对比，二三维时 保存的geojson文件中的 飞机的坐标， 两者的坐标完全一模一样；就是页面显示的视觉上有差异；

三维截图：
![飞机三维](https://github.com/marsgis/mars3d-vue-example/assets/2908276/06ae3d63-ae82-4dc6-b583-9a62eb71b312)

二维截图：
![飞机二维](https://github.com/marsgis/mars3d-vue-example/assets/2908276/bcaffb26-b25d-408f-b8ad-2493e07ae5ea)

**Comment by muyao1987** [comment]
应该是cesium新版本改造后出现的问题，2D下模型有个 "projectTo2D":true, 参数，但目前测试加了后直接报错了，需要等后面新版本cesium解决。
