### ISSUE TITLE
Mars-dialog框中，按control, f12报错：“e.lastError: The message port closed before a response was received.”

### ISSUE THREAD

**Issue by liseri** [marsgis/mars3d-vue-example#12]
示例： http://mars3d.cn/editor-vue.html?id=graphic/divGraphic/basis
右侧Mars-dialog框中，按control键, f12报错：“e.lastError: The message port closed before a response was received.”

**Comment by muyao1987** [comment]
未能复现，可以加微信群反馈下具体步骤。
http://mars3d.cn/community.html

**Comment by liseri** [comment]
已进群；任何一个dialog， 1）先打开f12； 2）鼠标移进dialog中，确保鼠标的focus是在dialog中(比如操作一下dialog); 3）键盘按control键； console中就会报错：“e.lastError: The message port closed before a response was received.”

**Comment by liseri** [comment]
清除浏览器缓存后就好了； 以后再出现的话 再说吧， 感谢！！
