### ISSUE TITLE
echarts无法触发 click 等事件

### ISSUE THREAD

**Issue by myjustify** [marsgis/mars3d-vue-example#14]
我在官方的案例中 [官方示例](http://mars3d.cn/editor-vue.html?id=layer-other/echarts/lines-liuchu)
createEchartsLayer函数中 添加了 
```
echartsLayer.on('click', () => {
    console.log(111)
})
```
但是怎么都不会触发

**Comment by muyao1987** [comment]
需要参考这个示例开启交互
http://mars3d.cn/editor-vue.html?id=layer-other/echarts/effectScatter-gdp
![image](https://github.com/marsgis/mars3d-vue-example/assets/18432449/91f61f6c-758d-463d-a5c3-1ba4fddd6c46)
