### ISSUE TITLE
build 完页面 报map.js里的import  错

### ISSUE THREAD

**Issue by fortune-fu** [marsgis/mars3d-vue-example#2]
build 完页面 报map.js里的import  错，应该是不识别es6的语法
![image](https://user-images.githubusercontent.com/15607249/165013011-6a0a2978-8104-49ad-8906-9e32d76ff2c3.png)

**Comment by muyao1987** [comment]
read.html页面目前还不支持build后的使用，仅dev开发时可用。
原因是里面import语法在浏览器不支持，后续我们有时间时优化下。
也可以editor页面传入full=1参数达到read页面类似效果。

如：http://mars3d.cn/editor.html?id=layer-tile/type/xyz&full=1
