### ISSUE TITLE
Uncaught (in promise) Error: container 不能为空     at e.Editor.renderContainer (editor.umd.js:9:32996)     at e.Editor.render (editor.umd.js:9:62941)     at main.ts:78:12

### ISSUE THREAD

**Issue by atgczcl** [marsgis/mars3d-vue-example#5]
![image](https://user-images.githubusercontent.com/236108/209659353-3989632f-fea2-42ca-a547-35044bd90ebe.png)
Uncaught (in promise) Error: container 不能为空
    at e.Editor.renderContainer (editor.umd.js:9:32996)
    at e.Editor.render (editor.umd.js:9:62941)
    at main.ts:78:12

随便点一个example, 报错这个跑不起来

**Comment by muyao1987** [comment]
应该已经修复了，可以使用最新v3.5版本
