### ISSUE TITLE
启动报错 [ERROR] Could not resolve "mars3d-cesium"

### ISSUE THREAD

**Issue by zyjqjnh** [marsgis/mars3d-vue-example#7]
[ERROR] Could not resolve "mars3d-cesium"

    node_modules/mars3d/dist/mars3d.js:10:108:
      10 │ ...rts, (window.Cesium || require('mars3d-cesium')), (window.turf || require('@t...
         ╵                                   ~~~~~~~~~~~~~~~

  You can mark the path "mars3d-cesium" as external to exclude it from the bundle, which will  
  remove this error. You can also surround this "require" call with a try/catch block to       
  handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "@turf/turf"

    node_modules/mars3d/dist/mars3d.js:10:151:
      10 │ ...w.Cesium || require('mars3d-cesium')), (window.turf || require('@turf/turf'))) : 
         ╵                                                                   ~~~~~~~~~~~~      

  You can mark the path "@turf/turf" as external to exclude it from the bundle, which will     
  remove this error. You can also surround this "require" call with a try/catch block to       
  handle this failure at run-time instead of bundle-time.

node版本14.18.0 尝试切换到18.15.0 也还是报同样的错误

**Comment by muyao1987** [comment]
没有复现问题，我拉了一个最新仓库代码，npm i 后 npm run serve正常运行成功了
![image](https://user-images.githubusercontent.com/18432449/226906091-47962e6f-f5af-4397-8f77-0032b1a712d2.png)
