### ISSUE TITLE
fixedRoute的mars3d.EventType.endItem事件有问题

### ISSUE THREAD

**Issue by liseri** [marsgis/mars3d-vue-example#8]
版本： 3.5.0
问题描述：
1. 定义一个有3个点的fixedRoute任务，定义为第0点(起点)，第1点，第2点(终点)
2. 使用如下代码检测漫游节点
```
fixedRoute.on(mars3d.EventType.endItem, function (event) {
    console.log("已漫游过点：" + event.index, event)
  })
```
3. 问题
- 任务start后，count为3； 
- 第0个点(起点)启动后接收事件打印"已漫游过点0"，点坐标为第0点坐标，**正确**
- 几毫秒后紧接着打印"已漫游过点1"，事件中点坐标为第1点坐标，事实上刚刚启动，远没有到达第1点， **错误**
- 到达第1个点后，打印”已漫游过点2“，事件中点坐标为第2点(终点)坐标，事实上刚到达第1点， **错误**
- 到达第2个点(终点后)，没有接收到endItem事件

**Comment by liseri** [comment]
还测到一个漫游过点endItem事件相关的问题，那就是 如果将clock调成-1他会往回走，经过某个漫游点的时候，触发了相同的事件多次，我测的是8次； 正常来讲到达某个点的时候，只触发一次；

**Comment by muyao1987** [comment]
可以升级到最新3.5.15看下
